-- добавить связь
GO
CREATE PROCEDURE AddUtoA
 @ID_USER INT,
 @ID_ACHIEVEMENT INT
AS
BEGIN
	INSERT INTO User_To_Achievement([ID_USER],[ID_ACHIEVEMENT]) 
	VALUES(@ID_USER, @ID_ACHIEVEMENT)
END

-- удалить связь
GO
CREATE PROCEDURE RemoveUtoA
@ID_USER INT,
@ID_ACHIEVEMENT INT
AS
BEGIN
	DELETE FROM User_To_Achievement
	WHERE ID_USER = @ID_USER AND ID_ACHIEVEMENT = @ID_ACHIEVEMENT
END

-- удалить пользователя
GO
CREATE PROCEDURE RemoveUserUtoA
@ID_USER INT
AS
BEGIN
	DELETE FROM User_To_Achievement
	WHERE ID_USER = @ID_USER
END

-- удалить достижение
GO
CREATE PROCEDURE RemoveAchievementUtoA
@ID_ACHIEVEMENT INT
AS
BEGIN
	DELETE FROM User_To_Achievement
	WHERE ID_ACHIEVEMENT = @ID_ACHIEVEMENT
END
